#!/bin/bash

#BSD-2-Clause
#Copyright (c) 2017, c-rho-272 (PR_SOT, PR_713)
#All rights reserved.
#
#Redistribution and use in source and binary forms, with or without
#modification, are permitted provided that the following conditions are met:
#
#* Redistributions of source code must retain the above copyright notice, this
#  list of conditions and the following disclaimer.
#* Redistributions in binary form must reproduce the above copyright notice,
#  this list of conditions and the following disclaimer in the documentation
#  and/or other materials provided with the distribution.
#
#THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
#LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#POSSIBILITY OF SUCH DAMAGE.

announcers=()
watchers=()
notifiers=()


function add_announcer {
	if [ "$1" != "" ]; then
		announcers+=($1)
	fi
}

function add_notifier {
	if [ "$1" != "" ]; then
		notifiers+=($1)
	fi
}

function add_watcher {
	if [ "$1" != "" ]; then
		watchers+=($1)
	fi
}

for f in "$prog_root"/*.plugin; do
	source "$f"
done


function announce {
	for announcer in "${announcers[@]}"; do
		if [ "$announcer" != "" ]; then
			$announcer "$@"
		fi
	done
}

function notify {
	for notifier in "${notifiers[@]}"; do
		if [ "$notifier" != "" ]; then
			$notifier "$@"
		fi
	done
}

function start_watchers {
	for watcher in "${watchers[@]}"; do
		if [ "$watcher" != "" ]; then
			$watcher &
		fi
	done
}
